import os
from datetime import datetime
from typing import Optional
from core.config import config


MARKDOWN_TEMPLATE = """# {title}

**Engagement Type:** {engagement_type}
**Date:** {date}
**Analyst:** Consulting Agent AI

---

## Executive Summary

{executive_summary}

---

## Table of Contents

1. [Background & Context](#background--context)
2. [Analysis](#analysis)
3. [Frameworks Applied](#frameworks-applied)
4. [Key Findings](#key-findings)
5. [Recommendations](#recommendations)
6. [Risk Assessment](#risk-assessment)
7. [Appendix: Data Sources & Methodology](#appendix-data-sources--methodology)

---

## Background & Context

{background}

---

## Analysis

{analysis}

---

## Frameworks Applied

{frameworks}

---

## Key Findings

{findings}

---

## Recommendations

{recommendations}

---

## Risk Assessment

{risks}

---

## Appendix: Data Sources & Methodology

{sources}

---

*Generated by Consulting Agent AI | {date}*
"""


def generate_deliverable(
    title: str,
    engagement_type: str,
    sections: dict,
    output_format: str = "md",
) -> str:
    content = MARKDOWN_TEMPLATE.format(
        title=title,
        engagement_type=engagement_type.title(),
        date=datetime.now().strftime("%B %d, %Y"),
        executive_summary=sections.get("executive_summary", "TBD"),
        background=sections.get("background", "TBD"),
        analysis=sections.get("analysis", "TBD"),
        frameworks=sections.get("frameworks", "TBD"),
        findings=sections.get("findings", "TBD"),
        recommendations=sections.get("recommendations", "TBD"),
        risks=sections.get("risks", "TBD"),
        sources=sections.get("sources", "TBD"),
    )

    os.makedirs(config.OUTPUT_DIR, exist_ok=True)

    safe_name = title.lower().replace(" ", "_").replace("/", "_")[:50]
    md_path = os.path.join(config.OUTPUT_DIR, f"{safe_name}.md")

    with open(md_path, "w") as f:
        f.write(content)

    if output_format == "pdf":
        return _convert_to_pdf(md_path)

    return md_path


def _convert_to_pdf(md_path: str) -> str:
    pdf_path = md_path.replace(".md", ".pdf")
    try:
        import markdown
        from weasyprint import HTML

        with open(md_path, "r") as f:
            html_content = markdown.markdown(f.read())

        html_with_style = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; margin: 2cm; }}
h1 {{ color: #1a1a2e; border-bottom: 3px solid #1a1a2e; padding-bottom: 10px; }}
h2 {{ color: #16213e; margin-top: 30px; }}
h3 {{ color: #0f3460; }}
strong {{ color: #1a1a2e; }}
</style>
</head>
<body>
{html_content}
</body>
</html>"""

        HTML(string=html_with_style).write_pdf(pdf_path)
        return pdf_path
    except Exception as e:
        return f"PDF generation failed (install weasyprint): {e}. MD saved at: {md_path}"
